name: Release

on:
  push:
    tags: ["v*"]  # Trigger on tags like v1.0.0

jobs:
  version-check:
    name: Verify version consistency
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify crate version matches release tag
        run: |
          CRATE_VERSION=$(grep -m1 '^version' Cargo.toml | cut -d '"' -f 2)
          if [[ "v$CRATE_VERSION" != "${{ github.ref_name }}" ]]; then
            echo "Error: Cargo.toml version ($CRATE_VERSION) doesn't match release tag (${{ github.ref_name }})"
            exit 1
          fi

  build:
    name: Build (${{ matrix.platform }})
    needs: version-check  # Wait for version validation
    strategy:
      matrix:
        include:
          - platform: linux
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            binary_name: loss-linux
          - platform: macos
            target: x86_64-apple-darwin
            os: macos-latest
            binary_name: loss-macos
          - platform: windows
            target: x86_64-pc-windows-gnu
            os: windows-latest
            binary_name: loss-windows.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary
        run: mv target/${{ matrix.target }}/release/${{ matrix.binary_name }} ${{ matrix.binary_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-binary
          path: ${{ matrix.binary_name }}

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all binaries
        uses: actions/download-artifact@v4
        with:
          path: release_binaries
          pattern: '*-binary'
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          files: |
            release_binaries/loss-linux
            release_binaries/loss-macos
            release_binaries/loss-windows.exe
          generate_release_notes: true