name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  version-check:
    name: Verify version consistency
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify crate version matches release tag
        run: |
          CRATE_VERSION=$(grep -m1 '^version' Cargo.toml | cut -d '"' -f 2)
          if [[ "v$CRATE_VERSION" != "${{ github.ref_name }}" ]]; then
            echo "Error: Cargo.toml version ($CRATE_VERSION) doesn't match release tag (${{ github.ref_name }})"
            exit 1
          fi

  publish-crates:
    name: Publish crates
    needs: version-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish --verbose

  build:
    name: Build (${{ matrix.platform }})
    needs: version-check
    strategy:
      matrix:
        include:
          - platform: linux
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            binary_name: loss
          - platform: linux
            target: x86_64-unknown-linux-gnu
            os: ubuntu-18.04
            binary_name: loss
          - platform: macos
            target: x86_64-apple-darwin
            os: macos-latest
            binary_name: loss
          - platform: windows
            target: x86_64-pc-windows-gnu
            os: windows-latest
            binary_name: loss.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary
        working-directory: ${{ runner.workspace }}/Loss/
        env:
          label: ${{ matrix.os }}-${{ matrix.target }}
        run: |
          mkdir loss-${{ env.label }}
          mv target/${{ matrix.target }}/release/${{ matrix.binary_name }} loss-${{ env.label }}/
          mv README.md loss-${{ env.label }}/
          mv LICENSE loss-${{ env.label }}/
          mv docs/changelog loss-${{ env.label }}/
          tar -czvf loss-${{ env.label }}.tar.gz loss-${{ env.label }}/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: loss-${{ env.label }}.tar.gz
          path: loss-${{ env.label }}.tar.gz

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all binaries
        uses: actions/download-artifact@v4
        with:
          path: release_binaries
          pattern: 'loss-*.tar.gz'
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "${{ github.ref_name }}"
          files: |
            release_binaries/loss-ubuntu-latest-x86_64-unknown-linux-gnu.tar.gz
            release_binaries/loss-ubuntu-18.04-x86_64-unknown-linux-gnu.tar.gz
            release_binaries/loss-macos-latest-x86_64-apple-darwin.tar.gz
            release_binaries/loss-windows-latest-x86_64-pc-windows-gnu.tar.gz
          generate_release_notes: true